enum FileBuilder {
    static func fileContents(with enumString: String, filename: String) -> String {
        return """
        // \(filename)
        // Generated by Shark https://github.com/kaandedeoglu/Shark
        
        import UIKit
        
        // swiftlint:disable all
        \(enumString)
        """
    }
}
