enum FileBuilder {
    static func fileContents(with enumString: String, options: Options) -> String {

        let importStatements = options.frameworks.map { $0.importStatement }.joined(separator: "\n")

        return """
        // \(options.outputPath.lastPathComponent)
        // Generated by Shark https://github.com/kaandedeoglu/Shark
        
        \(importStatements)

        // swiftlint:disable all
        // swiftformat:disable all
        \(enumString)

        """
    }
}
